# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16u48EWG50C0h7e9fpTHJj3BbZfClAZfi
"""

!pip -q install geopandas rasterio scipy pillow matplotlib

from google.colab import files
uploaded = files.upload()

print("업로드된 파일:")
for name in uploaded.keys():
    print(name)

from pathlib import Path
import json
import math

import numpy as np
import pandas as pd
import geopandas as gpd
import rasterio

from shapely.geometry import mapping
from scipy.ndimage import gaussian_filter

from rasterio.features import rasterize, geometry_mask
from rasterio.transform import from_origin, array_bounds
from rasterio.enums import MergeAlg, Resampling
from rasterio.warp import calculate_default_transform, reproject

from pyproj import Transformer
from PIL import Image
from matplotlib import colormaps


# ============================================================
# 1. 사용자 설정
# ============================================================

CSV_PATH = "/content/CCTV정보_서울송파구.csv"
BOUNDARY_PATH = "/content/songpa_boundary_approx_from_cctv.geojson"

# 범죄·안전 관련 분석이면 생활방범 권장
# 모든 목적을 포함하려면 None
PURPOSES = None
# False: 동일 위치를 1개의 CCTV 지점으로 취급
# True: 카메라대수를 가중치로 사용
WEIGHT_BY_CAMERA = True

BANDWIDTH_M = 20.0       # KDE 거리 기준
CELL_SIZE_M = 5.0        # 출력 격자 해상도
TRUNCATE_SIGMA = 4.0     # 20m × 4 = 실질적으로 80m까지 계산

CRS_ANALYSIS = "EPSG:5186"   # 미터 단위 분석 좌표계
CRS_WEB = "EPSG:3857"        # Leaflet 표시용 좌표계

TIF_PATH = "/content/reverse_kde_20m_5186.tif"
PNG_PATH = "/content/reverse_kde_20m_web.png"
META_PATH = "/content/reverse_kde_20m_meta.json"

NODATA = -9999.0


# ============================================================
# 2. CSV 불러오기 및 정리
# ============================================================

df = pd.read_csv(CSV_PATH, encoding="cp949")

required_columns = [
    "WGS84위도",
    "WGS84경도",
    "설치목적구분",
    "카메라대수",
]

missing = [col for col in required_columns if col not in df.columns]
if missing:
    raise ValueError(f"필수 열이 없습니다: {missing}")

df["WGS84위도"] = pd.to_numeric(df["WGS84위도"], errors="coerce")
df["WGS84경도"] = pd.to_numeric(df["WGS84경도"], errors="coerce")
df["카메라대수"] = (
    pd.to_numeric(df["카메라대수"], errors="coerce")
    .fillna(1)
    .clip(lower=1)
)

df = df.dropna(subset=["WGS84위도", "WGS84경도"]).copy()

# 비정상 좌표 제거
df = df[
    df["WGS84위도"].between(-90, 90)
    & df["WGS84경도"].between(-180, 180)
].copy()

if PURPOSES is not None:
    df = df[df["설치목적구분"].isin(PURPOSES)].copy()

if df.empty:
    raise ValueError("선택 조건에 해당하는 CCTV가 없습니다.")


# ============================================================
# 3. 동일 좌표 통합
# ============================================================

coord_cols = ["WGS84위도", "WGS84경도"]

if WEIGHT_BY_CAMERA:
    point_table = (
        df.groupby(coord_cols, as_index=False)["카메라대수"]
        .sum()
        .rename(columns={"카메라대수": "weight"})
    )
else:
    point_table = df[coord_cols].drop_duplicates().copy()
    point_table["weight"] = 1.0


# ============================================================
# 4. 분석 좌표계로 변환
# ============================================================

points = gpd.GeoDataFrame(
    point_table,
    geometry=gpd.points_from_xy(
        point_table["WGS84경도"],
        point_table["WGS84위도"],
    ),
    crs="EPSG:4326",
).to_crs(CRS_ANALYSIS)

boundary = gpd.read_file(BOUNDARY_PATH)

if boundary.crs is None:
    raise ValueError("경계 파일에 좌표계 정보가 없습니다.")

boundary = boundary.to_crs(CRS_ANALYSIS)

if hasattr(boundary.geometry, "union_all"):
    boundary_geom = boundary.geometry.union_all()
else:
    boundary_geom = boundary.geometry.unary_union

if boundary_geom.is_empty:
    raise ValueError("송파구 경계가 비어 있습니다.")

# 송파구 안에 있는 CCTV만 사용
points = points.loc[
    points.geometry.intersects(boundary_geom)
].copy()

if points.empty:
    raise ValueError("송파구 경계 안에 CCTV가 없습니다.")


# ============================================================
# 5. 5m 격자 생성
# ============================================================

minx, miny, maxx, maxy = boundary_geom.bounds

width = max(1, math.ceil((maxx - minx) / CELL_SIZE_M))
height = max(1, math.ceil((maxy - miny) / CELL_SIZE_M))

# 래스터의 왼쪽 위 기준
transform = from_origin(
    minx,
    maxy,
    CELL_SIZE_M,
    CELL_SIZE_M,
)

# 같은 격자에 들어가는 CCTV는 가중치를 합산
shapes = (
    (geometry, float(weight))
    for geometry, weight in zip(
        points.geometry,
        points["weight"],
    )
)

point_raster = rasterize(
    shapes=shapes,
    out_shape=(height, width),
    transform=transform,
    fill=0.0,
    merge_alg=MergeAlg.add,
    dtype="float32",
)

# 송파구 행정경계 마스크
inside_mask = geometry_mask(
    [mapping(boundary_geom)],
    out_shape=(height, width),
    transform=transform,
    invert=True,
    all_touched=False,
)


# ============================================================
# 6. 20m Gaussian KDE
# ============================================================

sigma_pixels = BANDWIDTH_M / CELL_SIZE_M

smoothed = gaussian_filter(
    point_raster,
    sigma=sigma_pixels,
    mode="constant",
    cval=0.0,
    truncate=TRUNCATE_SIGMA,
)

# 한 개 CCTV 지점의 중심 영향력이 정확히 1에 가깝도록 보정
radius_pixels = math.ceil(TRUNCATE_SIGMA * sigma_pixels)

impulse = np.zeros(
    (radius_pixels * 2 + 1, radius_pixels * 2 + 1),
    dtype="float32",
)
impulse[radius_pixels, radius_pixels] = 1.0

unit_kernel = gaussian_filter(
    impulse,
    sigma=sigma_pixels,
    mode="constant",
    cval=0.0,
    truncate=TRUNCATE_SIGMA,
)

unit_peak = float(unit_kernel[radius_pixels, radius_pixels])

if unit_peak <= 0:
    raise RuntimeError("Gaussian 커널 보정값을 계산하지 못했습니다.")

# KDE 영향력 표면
influence = smoothed / unit_peak

# 영향력이 1 이상이면 충분히 커버되는 것으로 간주
coverage = np.clip(influence, 0.0, 1.0)

# 역-KDE: 커버리지가 낮을수록 취약도 증가
vulnerability = 1.0 - coverage

# 송파구 밖은 표시하지 않음
vulnerability = np.where(
    inside_mask,
    vulnerability,
    np.nan,
).astype("float32")


# ============================================================
# 7. 수치 보존용 GeoTIFF 저장
# ============================================================

tif_array = np.where(
    np.isfinite(vulnerability),
    vulnerability,
    NODATA,
).astype("float32")

with rasterio.open(
    TIF_PATH,
    "w",
    driver="GTiff",
    height=height,
    width=width,
    count=1,
    dtype="float32",
    crs=CRS_ANALYSIS,
    transform=transform,
    nodata=NODATA,
    compress="deflate",
) as dst:
    dst.write(tif_array, 1)
    dst.set_band_description(1, "CCTV reverse KDE vulnerability 0-1")


# ============================================================
# 8. Leaflet 표시용 EPSG:3857 래스터로 변환
# ============================================================

src_bounds = array_bounds(height, width, transform)

dst_transform, dst_width, dst_height = calculate_default_transform(
    CRS_ANALYSIS,
    CRS_WEB,
    width,
    height,
    *src_bounds,
)

web_array = np.full(
    (dst_height, dst_width),
    NODATA,
    dtype="float32",
)

reproject(
    source=tif_array,
    destination=web_array,
    src_transform=transform,
    src_crs=CRS_ANALYSIS,
    src_nodata=NODATA,
    dst_transform=dst_transform,
    dst_crs=CRS_WEB,
    dst_nodata=NODATA,
    resampling=Resampling.bilinear,
)

valid_web = web_array > -1000

web_values = np.where(
    valid_web,
    np.clip(web_array, 0.0, 1.0),
    np.nan,
)


# ============================================================
# 9. 투명 PNG 생성
#    녹색: 취약도 낮음 / 적색: 취약도 높음
# ============================================================

rgba = colormaps["RdYlGn_r"](
    np.nan_to_num(web_values, nan=0.0)
)

# 구 밖은 완전 투명
# 구 안은 HTML opacity와 별도로 PNG 자체 투명도 적용
rgba[..., 3] = np.where(valid_web, 0.78, 0.0)

image = Image.fromarray(
    (rgba * 255).astype("uint8"),
    mode="RGBA",
)

image.save(PNG_PATH, optimize=True)


# ============================================================
# 10. HTML 배치용 위경도 경계 저장
# ============================================================

left, bottom, right, top = array_bounds(
    dst_height,
    dst_width,
    dst_transform,
)

to_wgs84 = Transformer.from_crs(
    CRS_WEB,
    "EPSG:4326",
    always_xy=True,
)

west, south = to_wgs84.transform(left, bottom)
east, north = to_wgs84.transform(right, top)

metadata = {
    "bounds": [
        [south, west],
        [north, east],
    ],
    "bandwidth_m": BANDWIDTH_M,
    "cell_size_m": CELL_SIZE_M,
    "purposes": PURPOSES,
    "weight_by_camera": WEIGHT_BY_CAMERA,
    "point_count": int(len(points)),
    "vulnerability_min": float(
        np.nanmin(vulnerability)
    ),
    "vulnerability_max": float(
        np.nanmax(vulnerability)
    ),
}

Path(META_PATH).write_text(
    json.dumps(
        metadata,
        ensure_ascii=False,
        indent=2,
    ),
    encoding="utf-8",
)

print("완료")
print("CCTV 위치 수:", len(points))
print("GeoTIFF:", TIF_PATH)
print("HTML용 PNG:", PNG_PATH)
print("HTML 경계값:", META_PATH)
print("Leaflet bounds:", metadata["bounds"])

import json
from pathlib import Path

meta = json.loads(
    Path("/content/reverse_kde_20m_meta.json").read_text(encoding="utf-8")
)

meta["bounds"]